name: PR Notification

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify responsible colleague
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const reviewer = "LEI-110582  "; // substitui pelo GitHub username do colega
            const message = `👋 Olá @${reviewer}, este PR #${pr.number} precisa da tua revisão.`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: message
            });
